name: ML Model Test and Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --force-reinstall urllib3<2.0 requests<2.29.0 requests-toolbelt<1.0.0

    - name: Run model and tests
      run: |
        python src/model.py
        python src/test_model.py

    - name: Generate report
      run: python src/generate_report.py

    - name: Upload HTML report
      uses: actions/upload-artifact@v3
      with:
        name: ml-test-report
        path: ml_report.html
